name: seeds
description: SEEDS Wallet

version: 1.4.2+30

environment:
  sdk: ">=2.6.0 <3.0.0"

analyzer:
  enable-experiment: extension-methods

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^1.3.7
  cupertino_icons: ^0.1.3
  flutter_toolbox: ^4.6.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  flutter_secure_storage: ^3.3.2
  local_auth: ^0.6.2+3
  timeago: ^2.0.26
  cached_network_image: ^2.0.0
  intro_views_flutter:
    git: git://github.com/n13/IntroViews-Flutter
  flutter_masked_text: ^0.8.0
  passcode_screen: 1.2.2+1
  percent_indicator: ^2.1.1+1
  flutter_svg: ^0.18.1
  flutter_fluid_slider: ^1.0.2
  firebase_dynamic_links: ^0.6.2
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.3+1
  firebase_remote_config: ^0.4.2
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.1
  random_words: ^1.0.2
  share: ^0.6.4
  provider: ^4.0.5
  photo_view: ^0.9.1
  image_cropper: ^1.2.1
  sentry: ^3.0.1
  hive: ^1.4.4
  rxdart: ^0.24.0
  permission_handler: ^5.0.1
  qr_flutter: ^3.2.0
  eosdart_ecc:  ^0.4.3
  eosdart:
    git: git://github.com/JoinSEEDS/eosdart.git
  dart_esr:
    git:
      url: https://github.com/JoinSEEDS/dart-esr.git
  uni_links: ^0.4.0
  webview_flutter: ^1.0.7
  rubber: ^0.4.0
  path_provider: ^1.6.24
  dotted_border: ^1.0.6
  qr_code_scanner:
    git:
      url: git://github.com/triply-at/qr_code_scanner.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: any
  build_runner: ^1.8.1

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/ecosystem.svg
    - assets/images/app_icon.png
    - assets/images/app_icon_transparent.png
    - assets/images/loading.png
    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png
    - assets/images/onboarding/onboarding4.png
    - assets/images/onboarding/onboarding5.png
    - assets/images/governance.svg
    - assets/images/community.svg
    - assets/images/harvest.svg
    - assets/images/exchange.svg
    - assets/images/ecosystem.svg
    - assets/images/wallet.svg
    - assets/images/profile.svg
    - assets/images/logout.svg
    - assets/images/seeds.png
    - assets/images/seeds_light_wallet_logo.png
    - assets/images/guardians/guardian_tutorial_1.png
    - assets/images/guardians/guardian_tutorial_2.png
    - assets/images/guardians/guardian_tutorial_3.png
    - assets/images/guardians/guardian_tutorial_4.png
    - assets/images/guardians/guardian_shield.png
    # assets end

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900
