name: seeds
description: SEEDS Wallet

version: 1.4.2+32

environment:
  sdk: ">=2.6.0 <3.0.0"

analyzer:
  enable-experiment: extension-methods

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  url_launcher: ^5.7.10
  step_progress_indicator: ^0.2.5+8
  intl: ^0.16.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^1.3.7
  cupertino_icons: ^0.1.3
  flutter_toolbox: ^4.6.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  flutter_secure_storage: ^3.3.2
  local_auth: ^0.6.2+3
  timeago: ^2.0.26
  cached_network_image: ^2.0.0
  intro_views_flutter:
    git: git://github.com/n13/IntroViews-Flutter
  flutter_masked_text: ^0.8.0
  passcode_screen: 1.2.2+1
  percent_indicator: ^2.1.1+1
  flutter_svg: ^0.18.1
  flutter_fluid_slider: ^1.0.2
  firebase_dynamic_links: ^0.6.2
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.3+1
  firebase_remote_config: ^0.4.2
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.1
  random_words: ^1.0.2
  share: ^0.6.4
  provider: ^4.0.5
  photo_view: ^0.9.1
  image_cropper: ^1.2.1
  carousel_slider: ^3.0.0
  dots_indicator: ^1.2.0
  sentry: ^3.0.1
  hive: ^1.4.4
  rxdart: ^0.24.0
  permission_handler: ^5.0.1
  qr_flutter: ^3.2.0
  eosdart_ecc:  ^0.4.3
  eosdart:
    git: git://github.com/JoinSEEDS/eosdart.git
  dart_esr:
    git:
      url: https://github.com/JoinSEEDS/dart-esr.git
  uni_links: ^0.4.0
  webview_flutter: ^1.0.7
  rubber: ^0.4.0
  path_provider: ^1.6.24
  dotted_border: ^1.0.6
  pedantic: ^1.9.2
  qr_code_scanner:
    git:
      url: git://github.com/triply-at/qr_code_scanner.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: any
  build_runner: ^1.8.1

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/ecosystem.svg
    - assets/images/app_icon.png
    - assets/images/app_icon_transparent.png
    - assets/images/loading.png
    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png
    - assets/images/onboarding/onboarding4.png
    - assets/images/onboarding/onboarding5.png
    - assets/images/governance.svg
    - assets/images/community.svg
    - assets/images/harvest.svg
    - assets/images/exchange.svg
    - assets/images/ecosystem.svg
    - assets/images/wallet.svg
    - assets/images/profile.svg
    - assets/images/logout.svg
    - assets/images/lotus.svg
    - assets/images/lotus_support_small.svg
    - assets/images/lotus_support_big.svg
    - assets/images/seeds.png
    - assets/images/seeds_light_wallet_logo.png
    - assets/images/guardians/guardian_tutorial_1.png
    - assets/images/guardians/guardian_tutorial_2.png
    - assets/images/guardians/guardian_tutorial_3.png
    - assets/images/guardians/guardian_tutorial_4.png
    - assets/images/guardians/guardian_shield.png
    - assets/images/navigation_bar/explore.svg
    - assets/images/navigation_bar/wallet.svg
    - assets/images/navigation_bar/user_profile.svg
    - assets/images/navigation_bar/explore_selected.svg
    - assets/images/navigation_bar/wallet_selected.svg
    - assets/images/navigation_bar/user_profile_selected.svg
    - assets/images/explore/person_send_invite.svg
    - assets/images/explore/plant_seed.svg
    - assets/images/explore/thumb_up.svg
    - assets/images/key_guardians_icon.svg
    - assets/images/citizenship/reputation.svg
    - assets/images/citizenship/community.svg
    - assets/images/citizenship/planted.svg
    - assets/images/citizenship/age.svg
    - assets/images/citizenship/transaction.svg
    - assets/currency/aed.png
    - assets/currency/bdt.png
    - assets/currency/bzd.png
    - assets/currency/dkk.png
    - assets/currency/gip.png
    - assets/currency/inr.png
    - assets/currency/krw.png
    - assets/currency/mga.png
    - assets/currency/nad.png
    - assets/currency/pyg.png
    - assets/currency/sll.png
    - assets/currency/ttd.png
    - assets/currency/xaf.png
    - assets/currency/afn.png
    - assets/currency/bgn.png
    - assets/currency/cad.png
    - assets/currency/dop.png
    - assets/currency/gmd.png
    - assets/currency/iqd.png
    - assets/currency/kwd.png
    - assets/currency/mkd.png
    - assets/currency/ngn.png
    - assets/currency/qar.png
    - assets/currency/sos.png
    - assets/currency/twd.png
    - assets/currency/xcd.png
    - assets/currency/all.png
    - assets/currency/bhd.png
    - assets/currency/cdf.png
    - assets/currency/dzd.png
    - assets/currency/gnf.png
    - assets/currency/irr.png
    - assets/currency/kyd.png
    - assets/currency/mmk.png
    - assets/currency/nio.png
    - assets/currency/ron.png
    - assets/currency/srd.png
    - assets/currency/tzs.png
    - assets/currency/xof.png
    - assets/currency/amd.png
    - assets/currency/bif.png
    - assets/currency/chf.png
    - assets/currency/egp.png
    - assets/currency/gtq.png
    - assets/currency/isk.png
    - assets/currency/kzt.png
    - assets/currency/mnt.png
    - assets/currency/nok.png
    - assets/currency/rsd.png
    - assets/currency/std.png
    - assets/currency/uah.png
    - assets/currency/xpf.png
    - assets/currency/ang.png
    - assets/currency/bmd.png
    - assets/currency/clp.png
    - assets/currency/ern.png
    - assets/currency/gyd.png
    - assets/currency/jmd.png
    - assets/currency/lak.png
    - assets/currency/mop.png
    - assets/currency/npr.png
    - assets/currency/rub.png
    - assets/currency/svc.png
    - assets/currency/ugx.png
    - assets/currency/yer.png
    - assets/currency/aoa.png
    - assets/currency/bnd.png
    - assets/currency/cny.png
    - assets/currency/etb.png
    - assets/currency/hkd.png
    - assets/currency/jod.png
    - assets/currency/lbp.png
    - assets/currency/mro.png
    - assets/currency/nzd.png
    - assets/currency/rwf.png
    - assets/currency/syp.png
    - assets/currency/usd.png
    - assets/currency/zar.png
    - assets/currency/ars.png
    - assets/currency/bob.png
    - assets/currency/cop.png
    - assets/currency/eur.png
    - assets/currency/hnl.png
    - assets/currency/jpy.png
    - assets/currency/lkr.png
    - assets/currency/mur.png
    - assets/currency/omr.png
    - assets/currency/sar.png
    - assets/currency/szl.png
    - assets/currency/uyu.png
    - assets/currency/zmw.png
    - assets/currency/aud.png
    - assets/currency/brl.png
    - assets/currency/crc.png
    - assets/currency/fjd.png
    - assets/currency/hrk.png
    - assets/currency/kes.png
    - assets/currency/lrd.png
    - assets/currency/mvr.png
    - assets/currency/pen.png
    - assets/currency/sbd.png
    - assets/currency/thb.png
    - assets/currency/uzs.png
    - assets/currency/awg.png
    - assets/currency/bsd.png
    - assets/currency/cup.png
    - assets/currency/fkp.png
    - assets/currency/htg.png
    - assets/currency/kgs.png
    - assets/currency/ltl.png
    - assets/currency/mwk.png
    - assets/currency/pgk.png
    - assets/currency/scr.png
    - assets/currency/tjs.png
    - assets/currency/vef.png
    - assets/currency/azn.png
    - assets/currency/btn.png
    - assets/currency/cve.png
    - assets/currency/gbp.png
    - assets/currency/huf.png
    - assets/currency/khr.png
    - assets/currency/lyd.png
    - assets/currency/mxn.png
    - assets/currency/php.png
    - assets/currency/sek.png
    - assets/currency/tnd.png
    - assets/currency/vnd.png
    - assets/currency/bam.png
    - assets/currency/bwp.png
    - assets/currency/czk.png
    - assets/currency/gel.png
    - assets/currency/idr.png
    - assets/currency/kmf.png
    - assets/currency/mad.png
    - assets/currency/myr.png
    - assets/currency/pkr.png
    - assets/currency/sgd.png
    - assets/currency/top.png
    - assets/currency/vuv.png
    - assets/currency/bbd.png
    - assets/currency/byn.png
    - assets/currency/djf.png
    - assets/currency/ghs.png
    - assets/currency/ils.png
    - assets/currency/kpw.png
    - assets/currency/mdl.png
    - assets/currency/mzn.png
    - assets/currency/pln.png
    - assets/currency/shp.png
    - assets/currency/try.png
    - assets/currency/wst.png
    - assets/currency/npr.png
    - assets/currency/sar.png
    - assets/currency/sgd.png
    - assets/currency/xaf.png
    - assets/currency/xof.png
    - assets/images/wallet/arrow_up.svg
    - assets/images/wallet/arrow_down.svg
    - assets/images/wallet/app_bar/appbar_icon.svg
    - assets/images/wallet/app_bar/scan_qr_code_icon.svg
    - assets/images/wallet/app_bar/appbar_seeds_text.svg
    - assets/images/wallet/currency_info_cards/seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/seeds/background.jpg
    - assets/images/wallet/currency_info_cards/planted_seeds/background.jpg
    - assets/images/wallet/currency_info_cards/planted_seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/hypha/background.jpg
    - assets/images/wallet/currency_info_cards/hypha/logo.jpg
    # assets end

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick

      #DEPRECATED - DO NOT USE (worksans)
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay/SFProDisplay-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SFProDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Black.ttf
          weight: 900
