name: teloswallet
description: Telos Wallet

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

analyzer: 
  enable-experiment: extension-methods
   
dependencies:
  flutter:
    sdk: flutter
  intl:
  intl_translation:
  cupertino_icons: ^0.1.3
  community_material_icon: ^3.5.95
  http: ^0.12.0+4
  localstorage: ^3.0.1+4
  shared_preferences: ^0.5.6+1
  flutter_secure_storage: ^3.3.1+1
  local_auth: ^0.6.1
  timeago: ^2.0.26
  url_launcher: ^5.4.1
  cached_network_image: ^2.0.0
  intro_views_flutter:
    git: git://github.com/aagarwal1012/IntroViews-Flutter
  flutter_masked_text: ^0.8.0
  passcode_screen: ^1.0.2
  percent_indicator: ^2.1.1+1
  expandable: ^4.1.2
  flutter_svg: ^0.17.1
  flutter_fluid_slider: ^1.0.2
  firebase_dynamic_links: ^0.5.0+9
  eosdart: ^0.4.4
  eosdart_ecc: ^0.4.0
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.1
  random_words: ^1.0.2
  share: ^0.6.3+5
  provider: ^4.0.4
  basic_utils: ^2.4.8  
  photo_view: ^0.9.1
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.1
  sentry: ^3.0.1
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  intl_phone_number_input: ^0.3.0
  sms_autofill: ^1.2.0
  qr_mobile_vision: ^0.3.1
  uni_links: ^0.2.0
  chopper2: ^3.0.4
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.4
  hive_generator: ^0.7.0
  build_runner: ^1.7.4  

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/tools.svg
    - assets/images/accounts.svg
    - assets/images/endpoint.svg
    - assets/images/sellram.svg
    - assets/images/resources.svg
    - assets/images/success_circle.png
    - assets/images/scan.svg
    - assets/images/wallet.svg
    - assets/images/share.svg
    - assets/images/undelegatebw.svg
    - assets/images/buyram.svg
    - assets/images/delegatebw.svg
    - assets/images/launcher_icon.png
    - assets/images/logo_title.png
    - assets/images/error.svg
    - assets/images/logout.svg
    - assets/images/no_item_found.svg
    - assets/images/signrequest.svg
    - assets/images/failure.png
    - assets/images/success.svg
    - assets/images/tools_icon.png
    # assets end

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick
    - family: sfprotext
      fonts:
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Semibold.otf
          weight: 700
    - family: vistolsans
      fonts:
        - asset: assets/fonts/vistolsanslight/VistolSans-Light.otf
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900
