on: push
name: Build and release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: steebchen/flutter@v1.0.0
      with:
        args: pub get
    - uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --debug --split-per-abi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.seedswallet }}